# Generated by Django 2.1.7 on 2019-04-12 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('has_irb_cert', models.BooleanField()),
                ('external_irb_approval', models.BooleanField()),
                ('protocol', models.CharField(max_length=255)),
                ('instructions', models.FileField(upload_to='project/instructions')),
                ('is_no_deception', models.BooleanField()),
                ('has_grant_funding', models.BooleanField()),
                ('grant_agency', models.CharField(max_length=255)),
                ('grant_funds_released', models.DateField()),
                ('alt_source_funding', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('primary_investigators', models.ManyToManyField(blank=True, related_name='pi', to=settings.AUTH_USER_MODEL)),
                ('research_assistants', models.ManyToManyField(blank=True, related_name='ra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
