# Generated by Django 2.1.7 on 2019-03-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='collaborators',
        ),
    ]
