# Generated by Django 2.1.7 on 2019-04-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190424_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='alt_source_funding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='external_irb_approval',
        ),
        migrations.RemoveField(
            model_name='project',
            name='grant_agency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='grant_funds_released',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_grant_funding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_irb_cert',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_no_deception',
        ),
        migrations.RemoveField(
            model_name='project',
            name='protocol',
        ),
    ]
