# Generated by Django 2.1.7 on 2019-03-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190328_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Project Description'),
            preserve_default=False,
        ),
    ]
