# Generated by Django 2.1.7 on 2019-04-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_fileitem_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.Project'),
        ),
    ]
