# Generated by Django 2.1.7 on 2019-04-03 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190402_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/instructions'),
            preserve_default=False,
        ),
    ]
