# Generated by Django 2.1.7 on 2019-04-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='instructions',
            field=models.FileField(upload_to='project/instructions'),
        ),
    ]
