# Generated by Django 2.1.7 on 2019-04-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190426_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='irb_approval_method',
            field=models.CharField(choices=[('NYU', 'NYU'), ('CESS', 'CESS'), ('EXT', 'External')], default='CESS', max_length=3),
        ),
    ]
