# Generated by Django 2.1.7 on 2019-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_irb_approval_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='irb_approval_method',
            field=models.CharField(choices=[('NYU', 'NYU'), ('CES', 'CESS'), ('EXT', 'External')], default='CES', max_length=3),
        ),
    ]
