# Generated by Django 2.1.7 on 2019-03-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190305_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Economics', max_length=255),
            preserve_default=False,
        ),
    ]
